config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # config/routes.rb

  get 'auth/oauth2/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'

  get 'logout' => 'logout#logout'

  resources :users, only: [:edit, :update]

  resources :meetings do
    member do
      get :code
      resources :attendences
    end
  end

  namespace :api do
    namespace :v1 do
      resources :scans, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can :read, :all                 # allow everyone to read everything
    return unless user && user.admin?

    can :access, :rails_admin       # only allow admin users to access Rails Admin
    can :read, :dashboard           # allow access to dashboard
    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  validates_presence_of :name, :date
  belongs_to :created_by, class_name: 'User'

  def self.upcoming
    where('date::date >= now()::date')
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email
  validates_uniqueness_of :email
  has_secure_token :api_key

  def filled_out_profile?
    company_name.present?
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      skip_before_action :verify_authenticity_token

      def restrict_access_api
        authenticate_with_http_token do |token, options|
          @current_user = User.find_by(api_key: token)
        end
      end
    end
  end
end

app/controllers/api/v1/scans_controller.rb
module Api
  module V1
    class ScansController < BaseController
      before_action :restrict_access_api

      def create
        user_id = params.require(:user_id)
        meeting_id = params.require(:meeting_id)
        user = User.find(user_id)
        meeting = Meeting.find(meeting_id)

        already_checked_in = Attendence.find_by(user: user, meeting: meeting)

        if already_checked_in
          render status: :ok, json: { message: "Hey #{user.given_name}, you have already checked in." }
          return
        end

        attendence = Attendence.find_or_create_by!(user: user, meeting: meeting)

        render status: :ok, json: { message: "Welcome, #{user.given_name}! 👋" }
      end
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def restrict_access
    unless logged_in?
      session[:redirect_to] = request.fullpath
      redirect_to '/auth/auth0' 
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user])
  end

  def logged_in?
    current_user != nil
  end

  protected

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  before_action :restrict_access

  def new
    @meeting = Meeting.find(params.require(:id))
    @attendence = Attendence.new(meeting: @meeting)
  end

  def create
    @meeting = Meeting.find(params.require(:id))
    @attendence = Attendence.find_or_create_by!(meeting: @meeting, user: current_user)
    flash[:success] = "Checked in!"
    redirect_to @meeting
  end
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # This stores all the user information that came from Auth0
    # and the IdP
    session[:userinfo] = request.env['omniauth.auth']
    user_info = request.env['omniauth.auth'].extra.raw_info.to_h.symbolize_keys
    user = User.create_with(user_info.slice(:name, :given_name, :family_name, :picture)).find_or_create_by!(user_info.slice(:email))
    session[:user] = user.id

    # Redirect to the URL you want after successful auth
    unless user.filled_out_profile?
      redirect_to edit_user_path(user.id) and return
    end

    redirect_to session[:redirect_to] || root_path
  end

  def failure
    # show a failure page or redirect to an error page
    @error_msg = request.params['message']
  end
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/' unless session[:userinfo].present?
  end
end

app/controllers/home_controller.rb
require 'rqrcode'

class HomeController < ApplicationController
  def show
    if logged_in?
      # @meetings = Meeting.upcoming
      @meetings = Meeting.all
    end
  end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  include LogoutHelper

  def logout
    reset_session
    redirect_to logout_url.to_s
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :restrict_access

  def show
    @meeting = Meeting.find(params.require(:id))
  end

  def code
    send_data(RQRCode::QRCode.new(new_attendence_url(id: params.require(:id), check_in: true)).as_png(
      fill: 'white',
      color: 'black',
      border_modules: 0,
    ), type: 'image/png', disposition: 'inline')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :restrict_access
  before_action :find_user
  before_action :require_user_to_be_logged_in_user
   
  def edit
  end

  def update
    first_time = !@user.filled_out_profile?

    @user.update!(update_user_params)

    if first_time
      redirect_to session[:redirect_to] || root_path
    else
      redirect_to root_path
    end
  end

  private

  def update_user_params
    params.require(:user).permit(:company_name)
  end

  def find_user
    if params[:id] == 'me'
      @user = current_user
    else
      @user = User.find(params.require(:id))
    end
  end

  def require_user_to_be_logged_in_user
    if @user.id != session[:user]
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_qr_code(qr)
    content_tag :div, class: 'qr' do
      raw(@qr.as_html)
    end
  end

  def page_header(text)
    content_tag :h1, text, class: 'display-3'
  end

  def format_date(date)
    date.strftime('%A, %B %e, %Y at %l:%M %p')
  end

  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
      else "alert alert-info"
    end
  end
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
  def logout_url
    domain = ENV.fetch('AUTH0_DOMAIN')
    client_id = ENV.fetch('AUTH0_CLIENT_ID')
    request_params = {
      returnTo: root_url,
      client_id: client_id
    }

    URI::HTTPS.build(host: domain, path: '/v2/logout', query: to_query(request_params))
  end

  private

  def to_query(hash)
    hash.map { |k, v| "#{k}=#{URI.escape(v)}" unless v.nil? }.reject(&:nil?).join('&')
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendences/new.html.erb
<%= page_header(@meeting.name) %>

<%= form_for @attendence, html: { id: :attendence_form } do |f|  %>
<%= f.submit "Check in", class: "btn btn-primary btn-lg btn-block" %>
<% end %>

<script>
document.addEventListener("DOMContentLoaded", function() {
  if (window.location.search.match(/check_in/)) {
    document.getElementById('attendence_form').submit();
  }
})
</script>

app/views/home/_logged_out.html.erb
<%= page_header("Welcome!") %>

<p><%= link_to 'Sign in', '/auth/auth0' %> before your meeting to:</p>

<ul>
  <li>Check in</li>
  <li>View the agenda</li>
</ul>

app/views/home/show.html.erb
<% if logged_in? %>
<%= page_header('Upcoming') %>

<% @meetings.each do |meeting| %>
<h2>
  <%= link_to meeting.name, meeting %>
  <small class="text-muted">on <%= format_date(meeting.date) %></small>
</h2>
<% end %>
<% else %>
<%= render partial: 'logged_out'%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <%= link_to 'JDRF YLC Meetings', root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
              </li>
              <% if can?(:access, :rails_admin) %>
                <li class="nav-item">
                  <%= link_to 'Admin', rails_admin_path, class: 'nav-link' %>
                </li>
              <% end %>
            </ul>
            <ul class="navbar-nav ml-auto">
              <% if logged_in? %>
                <%= link_to current_user.name, edit_user_path(current_user), class: 'nav-link' %>
                <%= link_to('Logout', logout_path, class: 'nav-link')%>
              <% else %>
                <%= link_to('Login', '/auth/auth0', class: 'nav-link') %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/meetings/scan.html.erb
SCANNER HERE

app/views/meetings/show.html.erb
<%= page_header @meeting.name %>
<% if current_user.admin? %>
<%= image_tag(code_meeting_url(@meeting.id), class: 'qr') %>
<% end %>
<h2>Agenda</h2>
<%= raw(@meeting.agenda) %>

app/views/users/edit.html.erb
<%= page_header('Edit Profile') %>

<%= form_for @user do |f| %>
  <%= f.label :company_name  %>
  <%= f.text_field :company_name, class: 'form-control' %>
  <%= f.label :phone  %>
  <%= f.text_field :phone, class: 'form-control' %>
  <%= f.submit "Update profile", class: 'btn btn-primary' %>
<% end %>